name: Golang workflow
on:
  pull_request:
  push:
    branches:
      - develop
      - master
  create:
    tags:
      - v*

jobs:
  commitlint:
    name: Check commit message format
    runs-on: ubuntu-latest
    steps:
      - uses: scaule/action-conventional-commits@master
